### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by jendiamond** [BitsBytesAI/feminist_ai_projects#10]
### Commit f52e3084ecf356ac7ccdbeb8d4c2419c9c714c47

**Comment by BitsBytesAI** [comment]
This project emerges from a MFA thesis in Media Design Practices at ArtCenter College of Design. This work examines the design implications of a Feminist Artificial Intelligence while considering the following design questions:

How can we co-author designs for embodiment in AI?
How can we call attention to the disembodiment of the female in AI models?
How can we incorporate cultural and social considerations in our AI design tools?

The Thesis Statement for this argument:

Early explorations of symbolic Artificial Intelligence, relying on the Turing Test, focused on methods to create a disembodied mind. Currently, the popular Artificial Neural Network computational model is based on biological neural networks in the human brain. However, both models still prioritize cognitive-sensory information and fail to account for the lived, social and cultural experiences of embodiment. This disembodiment is prevalent in AI development environments, which are overwhelmingly male, and the conceptual and physical designs of these systems often employ a highly sexualized or disembodied female form, implemented as an assistant or caretaker. This is evidenced in across various media including Japanese Manga, comics, popular films, AI dolls, and home and mobile smart devices.

Feminist theorists Alison Adam and Katherine Hayles posit that Artificial Intelligence should focus on addressing embodiment in the design and development of AI systems. Dara Blumenthal and Sara Ahmed consider embodiment to extend beyond the boundaries of the body, through the body-self, which they consider to be living, indefinite, and a mixture of bodily sensations, emotions, and thoughts, with the ability to shape the surfaces of individual and collective bodies. This approach expands on their ideas of embodiment in that rather than being confined to a body, we can understand the collective experience of fluid bodies formed by cultural emotions, while reflecting on Blumenthal's idea of embodiment beyond the enfleshed.

My response to hegemonic AI is through making:

These feminist AI projects explore design implications when making from a collaborative, feminist, post-human perspective. These two Feminist AI projects, the Post-human Plugin and Collaborative AI, explore a situated, re-embodiment of AI, from an experiential multi-sensory perspective while addressing social, cultural, material and post-human elements of embodiment. Collaborative AI is a direct response to the lack of women in AI development and brings multiple voices into AI creation through co-authoring. Post-human Plugin is a making response to the disembodiment of the female form in a household AI system, Alexa.
 
To read research about the history of AI and Embodiment from a feminist perspective, click here for the first half of the working paper. (https://drive.google.com/open?id=0Bz8lvCqH2p96NXdfc0VnaVF3QVk)

Below is the link to my presentation and video about Feminist AI Design, given at Machine Project on 4/1/17.

Machine Project Presentation:
https://drive.google.com/open?id=0Bz8lvCqH2p96STVWN3AzUVJoVFk

Video:
Embed code:

**Comment by BitsBytesAI** [comment]
the images are titled:
home_feminist-artificial-intelligence_about_collaborative
home_feminist-artificial-intelligence_home_about_posthuman

and are available here: 
https://www.dropbox.com/sh/wgzie9awkxm5hsq/AAC54azRTj94mfEo1owfc4Aya?dl=0

Let me know if you need more images in the home section.
